# Generated by Django 5.0.1 on 2024-02-11 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Carousel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("categoryName", models.CharField(max_length=30, null=True)),
                ("category", models.CharField(max_length=30, null=True)),
                ("offer", models.CharField(max_length=20)),
                ("brand", models.CharField(max_length=20, null=True)),
                ("img", models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brandName", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=100)),
                (
                    "clothingType",
                    models.CharField(
                        choices=[
                            ("Infant", "Infant"),
                            ("Topwear", "Topwear"),
                            ("Makeup", "Makeup"),
                            ("Skincare", "Skincare"),
                            ("Haircare", "Haircare"),
                            ("Footwear", "Footwear"),
                            ("Fragnance", "Fragnance"),
                            ("Sportswear", "Sportswear"),
                            ("Sportswear", "Sportswear"),
                            ("Sportswear", "Sportswear"),
                            ("Bottomwear", "Bottomwear"),
                            ("Indianwear", "Indianwear"),
                            ("Toys&Games", "Toys&Games"),
                            ("Boysclothing", "Boysclothing"),
                            ("Girlsclothing", "Girlsclothing"),
                            ("Men's Grooming", "Men's Grooming"),
                            ("Sleep&Innerwear", "Sleep&Innerwear"),
                            ("KidsAccessories", "KidsAccessories"),
                            ("FashionAccesscories", "FashionAccesscories"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "ProductTo",
                    models.CharField(
                        choices=[
                            ("Men", "men"),
                            ("Women", "women"),
                            ("Kids", "kids"),
                            ("Beauty", "beauty"),
                        ],
                        max_length=10,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("offerPrice", models.DecimalField(decimal_places=2, max_digits=10)),
                ("oldPrice", models.DecimalField(decimal_places=2, max_digits=10)),
                ("color", models.CharField(max_length=100)),
                ("thumbImg", models.URLField()),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Search",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                ("password", models.CharField(blank=True, max_length=12, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img", models.URLField(null=True)),
                ("message", models.TextField()),
                ("date", models.DateField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myntraData.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_material_detail", models.TextField()),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="productDetails",
                        to="myntraData.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MaterialCare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "product_detail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_care",
                        to="myntraData.productdetail",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.URLField()),
                ("alt", models.CharField(max_length=100)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="myntraData.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductSize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("size", models.CharField(max_length=10)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sizes",
                        to="myntraData.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.IntegerField()),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myntraData.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SizeFit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "product_detail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="size_fits",
                        to="myntraData.productdetail",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CartItems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_id", models.IntegerField()),
                ("quantity", models.IntegerField(default=1)),
                ("size", models.CharField(max_length=1)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myntraData.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BoughtProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_id", models.IntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myntraData.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("pincode", models.CharField(max_length=20)),
                ("state", models.CharField(max_length=20)),
                ("address", models.CharField(max_length=20)),
                ("town", models.CharField(max_length=20)),
                ("district", models.CharField(max_length=20)),
                ("addressType", models.CharField(max_length=20)),
                ("isDefault", models.BooleanField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myntraData.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WishLists",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_id", models.IntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myntraData.user",
                    ),
                ),
            ],
        ),
    ]
