# Generated by Django 5.0.1 on 2024-02-11 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myntraData", "0002_choice_question"),
    ]

    operations = [
        migrations.AlterField(
            model_name="choice",
            name="question_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="choices",
                to="myntraData.question",
            ),
        ),
    ]
