# Generated by Django 5.0.1 on 2024-02-12 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myntraData", "0003_alter_choice_question_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="choice",
            name="choice",
        ),
        migrations.RemoveField(
            model_name="choice",
            name="question_id",
        ),
        migrations.AddField(
            model_name="choice",
            name="choice_text",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="choice",
            name="question",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="myntraData.question",
            ),
        ),
    ]
