# Generated by Django 5.0.1 on 2024-02-12 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myntraData", "0004_remove_choice_choice_remove_choice_question_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="choice",
            name="question",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="choices",
                to="myntraData.question",
            ),
        ),
    ]
