# Generated by Django 5.0.1 on 2024-02-12 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myntraData", "0005_alter_choice_question"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boughtproduct",
            name="user",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="myntraData.user",
            ),
        ),
        migrations.AlterField(
            model_name="cartitems",
            name="user",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="myntraData.user",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="product",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="myntraData.product",
            ),
        ),
        migrations.AlterField(
            model_name="materialcare",
            name="product_detail",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="material_care",
                to="myntraData.productdetail",
            ),
        ),
        migrations.AlterField(
            model_name="productdetail",
            name="product",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="productDetails",
                to="myntraData.product",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="myntraData.product",
            ),
        ),
        migrations.AlterField(
            model_name="productsize",
            name="product",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sizes",
                to="myntraData.product",
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="product",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="myntraData.product",
            ),
        ),
        migrations.AlterField(
            model_name="sizefit",
            name="product_detail",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="size_fits",
                to="myntraData.productdetail",
            ),
        ),
        migrations.AlterField(
            model_name="useraddress",
            name="user",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="myntraData.user",
            ),
        ),
        migrations.AlterField(
            model_name="wishlists",
            name="user",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="myntraData.user",
            ),
        ),
    ]
