# Generated by Django 5.0.1 on 2024-02-12 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myntraData", "0007_alter_comment_product_alter_rating_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="materialcare",
            name="product_detail",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="materialcare",
                to="myntraData.productdetail",
            ),
        ),
        migrations.AlterField(
            model_name="productsize",
            name="product",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="size",
                to="myntraData.product",
            ),
        ),
        migrations.AlterField(
            model_name="sizefit",
            name="product_detail",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sizefit",
                to="myntraData.productdetail",
            ),
        ),
    ]
