# Generated by Django 5.0.1 on 2024-02-12 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myntraData", "0008_alter_materialcare_product_detail_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="catName",
            field=models.CharField(default="", max_length=100),
        ),
    ]
