# Generated by Django 5.0.1 on 2024-02-16 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myntraData", "0010_remove_boughtproduct_product_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="boughtproduct",
            name="product",
        ),
        migrations.CreateModel(
            name="ProductId",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("productId", models.IntegerField()),
                (
                    "bought_product",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="productIds",
                        to="myntraData.boughtproduct",
                    ),
                ),
            ],
        ),
    ]
