# Generated by Django 5.0.1 on 2024-02-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myntraData", "0011_remove_boughtproduct_product_productid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="thumbImg",
            field=models.URLField(max_length=500),
        ),
    ]
