# Generated by Django 5.0.1 on 2024-02-18 09:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myntraData", "0013_brandcategory_alter_product_clothingtype"),
    ]

    operations = [
        migrations.AddField(
            model_name="brandcategory",
            name="brandNameImg",
            field=models.URLField(default=""),
        ),
    ]
