# Generated by Django 5.0.1 on 2024-02-23 06:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myntraData", "0015_comment_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="pin_code",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
